version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: pip install --upgrade --user pip
      - run: pip install --upgrade --user pytest 
      - run: python3 main.py  # Run main script

  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: pip install --upgrade --user pip
      - run: pip install --upgrade --user pytest
      - run: python3 -m pytest test_main.py  # Run test script

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
